version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:2.4.0
    volumes:
      - type: volume
        target: /usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - node.hostname == w1