version: '3.2'

services:
  kibana:
    image: kibana:4.6.0
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"