# docker service create --name viz --publish 8090:8080 --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock --constraint=node.role==manager dockersamples/visualizer

version: '3.5'

services:
  viz:
    image: dockersamples/visualizer
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "8090:8080"
    deploy:
      placement:
        constraints:
          - node.role==manager
